name: porto

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil"]
    command: --odyssey --host 0.0.0.0 --port 8545
    labels:
      - dev.orbstack.domains=anvil.local
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 2s
      retries: 5

  config:
    depends_on:
      anvil:
        condition: service_healthy
    build:
      context: "${DOCKER_BUILD_CONTEXT}"
      dockerfile: ./docker/config/Dockerfile
    user: root
    environment:
      DOCKER_BUILD_CONTEXT: ${DOCKER_BUILD_CONTEXT:-https://github.com/ithacaxyz/porto.git}
    volumes:
      - relay:/app/shared
    command: ["sh", "-c", "bash ./run.sh"]

  relay:
    build:
      context: "${DOCKER_BUILD_CONTEXT}"
      dockerfile_inline: |
        FROM ghcr.io/ithacaxyz/relay:3fc0de2
        COPY --from=ghcr.io/foundry-rs/foundry:latest /usr/local/bin/cast /usr/local/bin/cast
    platform: linux/x86_64
    labels:
      - dev.orbstack.domains=relay.local
    ports:
      - "9119:9119"
    volumes:
      - relay:/app
    depends_on:
      config:
        condition: service_completed_successfully
    environment:
      RELAY_MNEMONIC: "test test test test test test test test test test test junk"
      DOCKER_BUILD_CONTEXT: ${DOCKER_BUILD_CONTEXT:-https://github.com/ithacaxyz/porto.git}
    command: --config-only --registry /app/registry.yaml
    healthcheck:
      test: ["CMD", "cast", "rpc", "--rpc-url", "http://localhost:9119", "health"]
      interval: 2s
      retries: 5

  proxy:
    build:
      context: "${DOCKER_BUILD_CONTEXT}"
      dockerfile: ./docker/proxy/Dockerfile
    labels:
      - dev.orbstack.domains=rpc.local
    environment:
      ANVIL_URL: http://anvil:8545
      RELAY_URL: http://relay:9119
      DOCKER_BUILD_CONTEXT: ${DOCKER_BUILD_CONTEXT:-https://github.com/ithacaxyz/porto.git}
      PORT: 9200
    ports:
      - "9200:9200"
      
volumes:
  relay: