[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src",
    "solady/=lib/solady/src",
]
via_ir = true
evm_version = "prague"
odyssey = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
